# Generated by Django 6.0.2 on 2026-03-14 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(choices=[('gatito', 'Gatito'), ('harry', 'Harry'), ('snape', 'Snape'), ('cuervo', 'Cuervo')], default='harry', max_length=20, upload_to=''),
        ),
    ]
