# Generated by Django 6.0.2 on 2026-02-16 15:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Encantos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('daño', models.IntegerField(default=0)),
                ('costo_mana', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='MatchRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('espera', 'Esperando a un jugador'), ('activo', 'Juego en curso'), ('terminado', 'Juego terminado')], default='espera', max_length=20)),
                ('nombre_room', models.CharField(max_length=255)),
                ('codigo', models.CharField(max_length=8, unique=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('ganador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ganador_room', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Jugador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hp', models.IntegerField(default=100)),
                ('mana', models.IntegerField(default=100)),
                ('turno', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='juego.matchroom')),
            ],
        ),
    ]
