# Generated by Django 6.0.2 on 2026-02-25 03:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('juego', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='encantos',
            old_name='nombre',
            new_name='encanto',
        ),
    ]
