# Generated by Django 6.0.2 on 2026-02-27 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juego', '0003_rename_nombre_encantos_encanto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='encantos',
            old_name='encanto',
            new_name='nombre',
        ),
        migrations.AlterField(
            model_name='encantos',
            name='tipo_encanto',
            field=models.CharField(choices=[('ataque', 'Ataque'), ('curacion', 'Curacion')], max_length=15),
        ),
        migrations.AlterField(
            model_name='matchroom',
            name='status',
            field=models.CharField(choices=[('espera', 'Esperando a un jugador'), ('activo', 'Juego en curso'), ('terminado', 'Partida terminado')], default='espera', max_length=20),
        ),
    ]
